const DOMStrings = {
  navigation:'.navigation',
  dividendTimer: 'p.dividend-timer',
  leftLmtRange: 'span.leftMark',
  rightLmtRange: 'span.rightMark',
  slideRange: '.sliderRangeInput input',
  multiplyval:'p.multie',
  winChanceVal:'p.WinChan',
  miningShine:'p.mineShine',
  betValue:'input#betAmout',
  payOutVal:'input#PayOut',
  RollBtn:'button.Rolling-btn',
  predictionVAl:'p.disNum',
  luckyDis:'p.disLuckyNum',
  directionToggle:'input.directionToggle',
  autoBetToggle:'input.autoToggler',
  ultraBetTogglr:'input.ultraToggler',
  minbtn:'button.minbtn',
  maxbtn:'button.maxbtn',
  halfbtn:'button.halfbtn',
  doublebtn:'button.doublebtn',
  myTrxbal:'.myTrxBal p span',
  toggleBtn: 'li.bar-icon',
  navList: 'ul.nav-list',
  dividendBtn:'li.dividendBtn',
  houseBtn:'li.houseBtn',
  profileBtn:'li.profileBtn',
  newsBtn:'li.newsBtn',
  infoBtn:'li.infoBtn',
  homeToggler:'.homeToggler',
  infoToggler:'.infoToggler',
  profileBox:'.profile-box',
  dividendBox:'.dividend-box',
  newsBox:'.news-box',
  mainPopUp:'.popub-bg',
  endPopUp: '.close-pop',
  chatBtn:'li.chat-icon',
  chatBox:'.left-side',
  rankBtn:'li.trophy-icon',
  rankBox:'.right-side',
  loginBtn:'li.userBtn button',
  allBetBtn:'li.allBetBtn',
  myBetBtn:'li.myBetsBtn',
  customBetBtn:'li.customBetBtn',
  allBetsBody:'.allbets',
  allbetTableBody:'.allbets table tbody',
  myBetsBody:'.myBets',
  mybetTableBody:'.myBets table tbody',
  customBetsBody:'.custombets',
  custombetTableBody:'.custombets table tbody',
  textareaBtn:'.textareaBtn',
  textmsgBox:'.textmsgBox textarea',
  minedInput:'input#withdraw-input',
  freezeInput:'input#freeze-input',
  unfreezeInput:'input#unfreeze-input',
  withdrawBtn:'.mined button',
  freezeBtn:'.frozen button',
  unfreezeBtn:'.unfreeze button',
  poolTrx:'p.poolTrx',
  disthisStageMined:'.meter p',
  disTotalMined:'span.tMined',
  disTotalFrozen:'span.tFrozen',
  dismyExpTRX:'span.tMyexpTRX',
  resultPop:'.resultPopUp',
  disMinedOnMain:'.MinedBal span',
  chatBody:'.chat-body',
  balanceAnim:'.balanceAnim',
  pendingBox:'.unfreezeApprove-box',
  approveBtn:'.unfreezeApprove-right button',
  disPendingAmt:'.unfreezeApprove-left span',
  disPendingTimer:'.unfreezeApprove-right span',
  headTokenToggle:'.token-toggler-header',
  TokenList:'.token-in-list',
  footTokenToggle:'.token-toggler-footer',
  togglerChanger:'span.toggler-arrow',
  disTokenWagerAndPool:'tbody.rankingBody',
  tokeninlistbody:'.token-in-list-body',
  disTokenBal:'p.myTokenBAl span',
  rankbtn:'li.leaderboard-icon',
  reffbtn:'li.reffBtn',
  aboutbtn:'li.aboutBtn',
  rankbox:'.rank-box',
  refbox:'.ref-box',
  aboutbox:'.about-box',
  disLink:'input#refLink',
  disActiveCount:'input#activeRef',
  totalRef:'input#visitorRef',
  refBonus:'input#earnedByRef',
  copyLink:'.myRefDiv button'
}
